name: Build EXEs and Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0, v2.1.3 etc.
  workflow_dispatch:
    inputs: {}


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Convert input to array
        id: parse
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.inputs.files }}" | tr ',' '\n' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build all EXEs (PowerShell)
        run: |
          $files = "scripts/tray.py,scripts/fetcher.py".Split(",")
          New-Item -ItemType Directory -Force -Path dist_exe | Out-Null
          foreach ($file in $files) {
            pyinstaller $file --onefile --noconsole --distpath dist_exe
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist_exe/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download EXEs
        uses: actions/download-artifact@v4
        with:
          name: all-exe
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
